import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  AIProvider,
  AIProviderOptions,
  AIProviderResponse,
} from './ai-provider.interface';
import { MockFallbackLLMProvider } from './fallback.provider';

@Injectable()
export class OpenAIProvider implements AIProvider {
  readonly name = 'OpenAIProvider';
  private readonly logger = new Logger(OpenAIProvider.name);

  constructor(
    private configService: ConfigService,
    private fallbackProvider: MockFallbackLLMProvider,
  ) {}

  private get apiKey(): string | null {
    return this.configService.get<string>('AI_API_KEY') || null;
  }

  private get model(): string {
    return this.configService.get<string>('AI_MODEL') || 'gpt-4o-mini';
  }

  private get baseUrl(): string {
    return (
      this.configService.get<string>('AI_BASE_URL') ||
      'https://api.openai.com/v1'
    );
  }

  async healthCheck(): Promise<boolean> {
    if (!this.apiKey) return false;
    try {
      const res = await fetch(`${this.baseUrl}/models`, {
        headers: { Authorization: `Bearer ${this.apiKey}` },
      });
      return res.ok;
    } catch {
      return false;
    }
  }

  async generateResponse(
    options: AIProviderOptions,
  ): Promise<AIProviderResponse> {
    if (!this.apiKey) {
      this.logger.log('No AI_API_KEY configured. Delegating to Fallback Knowledge Engine.');
      return this.fallbackProvider.generateResponse(options);
    }

    try {
      const systemPrompt =
        options.systemInstruction ||
        'You are LaunchPad Assistant, an enterprise SaaS app builder AI helper.';

      const formattedMessages = [
        { role: 'system', content: systemPrompt },
        ...options.messages.map((m) => ({
          role: m.role,
          content: m.content,
        })),
      ];

      const res = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          model: this.model,
          messages: formattedMessages,
          temperature: options.temperature || 0.7,
          max_tokens: options.maxTokens || 1000,
        }),
      });

      if (!res.ok) {
        const errorText = await res.text();
        this.logger.warn(
          `OpenAI API request failed (${res.status}): ${errorText}. Falling back to Knowledge Engine.`,
        );
        return this.fallbackProvider.generateResponse(options);
      }

      const data = await res.json();
      const content =
        data.choices?.[0]?.message?.content ||
        'No response generated by AI provider.';

      return {
        content,
        metadata: {
          provider: this.name,
          model: data.model || this.model,
        },
        usage: {
          promptTokens: data.usage?.prompt_tokens,
          completionTokens: data.usage?.completion_tokens,
          totalTokens: data.usage?.total_tokens,
        },
      };
    } catch (err: any) {
      this.logger.error(
        `OpenAI provider error: ${err.message}. Falling back to Knowledge Engine.`,
      );
      return this.fallbackProvider.generateResponse(options);
    }
  }

  async streamResponse(
    options: AIProviderOptions,
    onChunk: (chunk: string) => void,
  ): Promise<AIProviderResponse> {
    if (!this.apiKey) {
      return this.fallbackProvider.streamResponse(options, onChunk);
    }

    try {
      const systemPrompt =
        options.systemInstruction ||
        'You are LaunchPad Assistant, an enterprise SaaS app builder AI helper.';

      const formattedMessages = [
        { role: 'system', content: systemPrompt },
        ...options.messages.map((m) => ({
          role: m.role,
          content: m.content,
        })),
      ];

      const res = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          model: this.model,
          messages: formattedMessages,
          stream: true,
          temperature: options.temperature || 0.7,
          max_tokens: options.maxTokens || 1000,
        }),
      });

      if (!res.ok || !res.body) {
        return this.fallbackProvider.streamResponse(options, onChunk);
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder('utf-8');
      let fullContent = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split('\n').filter((l) => l.trim().startsWith('data: '));

        for (const line of lines) {
          const dataStr = line.replace(/^data:\s*/, '').trim();
          if (dataStr === '[DONE]') break;

          try {
            const parsed = JSON.parse(dataStr);
            const token = parsed.choices?.[0]?.delta?.content;
            if (token) {
              fullContent += token;
              onChunk(token);
            }
          } catch {
            // Ignore partial SSE JSON parse issues
          }
        }
      }

      return {
        content: fullContent,
        metadata: { provider: this.name, streamed: true },
      };
    } catch {
      return this.fallbackProvider.streamResponse(options, onChunk);
    }
  }
}
